// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6S8CNRt7mIa1s1Ce6gUD4qK1yKDOUrpM',
    appId: '1:382371099664:web:ba364b06e413fa74208695',
    messagingSenderId: '382371099664',
    projectId: 'yemek-asistani-506c9',
    authDomain: 'yemek-asistani-506c9.firebaseapp.com',
    storageBucket: 'yemek-asistani-506c9.firebasestorage.app',
    measurementId: 'G-YWMFD6QPYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjKKQMnU4lZjVfcdF_hBWnoBvvNtFTSI',
    appId: '1:382371099664:android:6e997253cc0ad9f4208695',
    messagingSenderId: '382371099664',
    projectId: 'yemek-asistani-506c9',
    storageBucket: 'yemek-asistani-506c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjKKQMnU4lZjVfcdF_hBWnoBvvNtFTSI',
    appId: '1:382371099664:ios:6e18940e32b7c453208695',
    messagingSenderId: '382371099664',
    projectId: 'yemek-asistani-506c9',
    storageBucket: 'yemek-asistani-506c9.firebasestorage.app',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjKKQMnU4lZjVfcdF_hBWnoBvvNtFTSI',
    appId: '1:382371099664:ios:6e18940e32b7c453208695',
    messagingSenderId: '382371099664',
    projectId: 'yemek-asistani-506c9',
    storageBucket: 'yemek-asistani-506c9.firebasestorage.app',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6S8CNRt7mIa1s1Ce6gUD4qK1yKDOUrpM',
    appId: '1:382371099664:web:ba364b06e413fa74208695',
    messagingSenderId: '382371099664',
    projectId: 'yemek-asistani-506c9',
    authDomain: 'yemek-asistani-506c9.firebaseapp.com',
    storageBucket: 'yemek-asistani-506c9.firebasestorage.app',
    measurementId: 'G-YWMFD6QPYS',
  );
}
